[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.93"
web-sys = { version = "0.3.70", features = [
    "Window",
    "Document",
    "HtmlElement",
    "Text",
] }
